import type { Metadata } from "next";
import Image from "next/image";
import Link from "@/components/link";
import { ArrowRight, Check } from "lucide-react";
import { PageHero, SiteFooter, SiteHeader } from "@/components/site-shell";

export const metadata: Metadata = { title: "Services", description: "Professional training, energy technical services, and business advisory from GELife Group." };

const services = [
  { id: "training", kicker: "People", title: "Professional Training & Workforce Development", copy: "Customized and self-paced programs that build relevant capability, strengthen leadership, and translate learning into workplace performance.", items: ["Self-paced professional course storefront and learner portal", "Customized corporate training programs", "Leadership and team-development workshops", "Energy and industry-specific technical training", "Virtual, in-person, and blended delivery"], image: "/images/business-team.png", alt: "A facilitator presenting a chart to a small group seated around a meeting table", link: "/training", cta: "Browse self-paced courses" },
  { id: "energy", kicker: "Energy", title: "Energy Technical Services", copy: "Practical, field-informed support that helps energy-sector teams manage technical complexity, strengthen decisions, and improve execution.", items: ["Drilling operations and performance support", "Formation evaluation and petrophysics workshops", "Well placement and geosteering advisory", "Technical operations reviews and risk reduction", "Energy transition capability and workforce readiness"], image: "/images/geosteering.png", alt: "Geosteering visualization with live subsurface data", link: "/contact?interest=Energy%20Technical%20Services", cta: "Discuss an energy project" },
  { id: "advisory", kicker: "Enterprise", title: "Business Transformation & Advisory", copy: "Structured guidance to help leaders clarify direction, improve operations, and move transformation initiatives from concept to execution.", items: ["Strategy and business transformation planning", "Operational optimization and process improvement", "Management consulting and performance reviews", "Digital transformation and ERP readiness", "Commercial opportunity development and brokerage support"], image: "/images/business-team.png", alt: "A business team reviewing documents while a colleague presents a growth chart", link: "/contact?interest=Business%20Advisory", cta: "Discuss a business priority" },
];

export default function ServicesPage() {
  return <><SiteHeader /><main><PageHero eyebrow="Our services" title="Focused expertise for people, energy, and enterprise."><p>Choose a service area and see how GELife Group can support your organization with practical learning, technical depth, and execution-focused advice.</p></PageHero><section className="section"><div className="site-shell space-y-10">{services.map((service, index) => <article id={service.id} key={service.id} className="surface grid scroll-mt-28 overflow-hidden lg:grid-cols-2"><div className={`p-7 sm:p-10 ${index % 2 ? "lg:order-2" : ""}`}><p className="eyebrow text-violet-700">{service.kicker}</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.035em] text-[#241033] sm:text-4xl">{service.title}</h2><p className="mt-4 text-lg leading-8 text-slate-600">{service.copy}</p><ul className="mt-6 space-y-3">{service.items.map((item) => <li key={item} className="flex gap-3 text-slate-700"><Check className="mt-0.5 shrink-0 text-amber-600" size={19} />{item}</li>)}</ul><Link href={service.link} className="button-primary mt-8">{service.cta} <ArrowRight size={18} /></Link></div><Image src={service.image} alt={service.alt} width={565} height={589} className={`h-full min-h-[360px] w-full object-cover ${index % 2 ? "lg:order-1" : ""}`} /></article>)}</div></section></main><SiteFooter /></>;
}
