import type { Metadata } from "next";
import Link from "@/components/link";
import { ArrowRight, Award, Clock3, KeyRound, SlidersHorizontal } from "lucide-react";
import { CourseCard } from "@/components/course-card";
import { PageHero, SiteFooter, SiteHeader } from "@/components/site-shell";
import { getPublishedCourses } from "@/lib/course-api";

export const metadata: Metadata = { title: "Self-Paced Professional Training", description: "Browse GELife Group's self-paced professional courses, enroll online, and learn through your secure learner portal." };

export default async function TrainingPage() {
  const courses = await getPublishedCourses();
  return <><SiteHeader /><main><PageHero eyebrow="GELife Learning" title="Professional learning, on your schedule."><p>Choose a practical course, generate your learner access, and build job-relevant capability through focused self-paced modules.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href="#catalog" className="button-primary">Browse current courses <ArrowRight size={18} /></a><Link href="/training/login" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/30 px-5 font-bold text-white hover:bg-white/10"><KeyRound size={18} /> Learner login</Link></div></PageHero><section className="border-b border-violet-100 bg-violet-50 py-7"><div className="site-shell grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[{ icon: Clock3, title: "Self-paced", text: "Study when your schedule allows." }, { icon: KeyRound, title: "Secure access", text: "Credentials are generated at enrollment." }, { icon: Award, title: "Practical", text: "Apply each lesson to real work." }, { icon: SlidersHorizontal, title: "Customizable", text: "Programs can be adapted for teams." }].map((item) => <div key={item.title} className="flex gap-3"><item.icon className="mt-1 shrink-0 text-[#421181]" size={23} /><div><strong className="text-[#241033]">{item.title}</strong><p className="mt-1 text-sm leading-6 text-slate-600">{item.text}</p></div></div>)}</div></section><section id="catalog" className="section scroll-mt-24"><div className="site-shell"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">Course catalog</p><h2 className="section-title">Start with a focused professional course.</h2></div><p className="max-w-lg leading-7 text-slate-600">Each course provides a practical foundation and is structured so GELife can expand the curriculum, examples, and assessments as the learning portfolio develops.</p></div><div className="mt-10 grid gap-6 md:grid-cols-2">{courses.map((course) => <CourseCard key={course.slug} course={course} />)}</div></div></section><section className="section bg-[#26104d] text-white"><div className="site-shell grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="eyebrow !text-[#ffb282]">Training for organizations</p><h2 className="mt-3 max-w-4xl text-4xl font-extrabold tracking-[-.04em] sm:text-5xl">Adapt a professional course into a program designed for your people.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-[#d7cee2]">Customize the examples, learning outcomes, assessments, delivery format, branding, and learner groups around your business goals.</p></div><Link href="/contact" className="button-primary">Request custom training <ArrowRight size={18} /></Link></div></section></main><SiteFooter /></>;
}
